name: Deploy Dash App to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Static Directory
        run: |
         ls -la static/ || echo "Static directory is missing!"
    

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r ./path/to/requirements.txt
        
          pip install selenium webdriver-manager

      - name: Generate Static HTML
        run: python generate_static.py  

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
          publish_branch: gh-pages
          force_orphan: true  # Ensures clean deployment
      
